### ISSUE TITLE
Failed to download the PGO profile for Win64

### ISSUE THREAD

**Issue by playgithub** [Nifury/ungoogled-chromium-windows#4]
Windows 11

```sh
λ set PATH=path\to\depot_tools;%PATH%
λ py build/src/tools/update_pgo_profiles.py --target=win64 update --gs-url-base=chromium-optimization-profiles/pgo_profiles
The system cannot find the file paht\to\depot_tools\python3_bin_reldir.txt.
```

depot_tools is download at
https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up

the actual download link is
https://storage.googleapis.com/chrome-infra/depot_tools.zip

**Comment by playgithub** [comment]
After running `gclient.bat`, errors as below
```bash
E:\ungoogled-chromium-windows>py build/src/tools/update_pgo_profiles.py --target=win64 update --gs-url-base=chromium-optimization-profiles/pgo_profiles
INFO 1010 10:47:28.044000 util.py] Retrying request, attempt #3...
INFO 1010 10:47:37.940000 util.py] Retrying request, attempt #4...
INFO 1010 10:47:57.836000 util.py] Retrying request, attempt #5...
INFO 1010 10:48:31.567000 util.py] Retrying request, attempt #6...
INFO 1010 10:49:06.234000 util.py] Retrying request, attempt #7...
INFO 1010 10:49:41.697000 util.py] Retrying request, attempt #8...
INFO 1010 10:50:16.425000 util.py] Retrying request, attempt #9...
INFO 1010 10:51:07.719000 util.py] Retrying request, attempt #10...
INFO 1010 10:51:42.524000 util.py] Retrying request, attempt #11...
INFO 1010 10:52:17.319000 util.py] Retrying request, attempt #12...
INFO 1010 10:52:52.053000 util.py] Retrying request, attempt #13...
INFO 1010 10:53:26.800000 util.py] Retrying request, attempt #14...
INFO 1010 10:54:01.504000 util.py] Retrying request, attempt #15...
INFO 1010 10:54:36.313000 util.py] Retrying request, attempt #16...
INFO 1010 10:55:11.072000 util.py] Retrying request, attempt #17...
INFO 1010 10:55:45.839000 util.py] Retrying request, attempt #18...
INFO 1010 10:56:20.604000 util.py] Retrying request, attempt #19...
INFO 1010 10:56:55.346000 util.py] Retrying request, attempt #20...
INFO 1010 10:57:30.201000 util.py] Retrying request, attempt #21...
INFO 1010 10:58:04.909000 util.py] Retrying request, attempt #22...
Traceback (most recent call last):
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gsutil", line 22, in <module>
    gsutil.RunMain()
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gsutil.py", line 114, in RunMain
    sys.exit(gslib.__main__.main())
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\__main__.py", line 381, in main
    perf_trace_token=perf_trace_token, user_project=user_project)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\__main__.py", line 567, in _RunNamedCommandAndHandleExceptions
    user_project=user_project)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\command_runner.py", line 319, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\commands\cp.py", line 1139, in RunCommand
    seek_ahead_iterator=seek_ahead_iterator)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\command.py", line 1372, in Apply
    arg_checker, should_return_results, fail_on_error)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\command.py", line 1418, in _SequentialApply
    args = args_iterator.next()
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\name_expansion.py", line 622, in next
    name_expansion_result = self.current_expansion_iter.next()
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\plurality_checkable_iterator.py", line 65, in _PopulateHead
    e = self.base_iterator.next()
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\name_expansion.py", line 265, in __iter__
    for (names_container, blr) in post_step3_iter:
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\plurality_checkable_iterator.py", line 65, in _PopulateHead
    e = self.base_iterator.next()
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\name_expansion.py", line 468, in __iter__
    for (names_container, blr) in self.tuple_iter:
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\plurality_checkable_iterator.py", line 65, in _PopulateHead
    e = self.base_iterator.next()
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\name_expansion.py", line 432, in __iter__
    for blr in self.blr_iter:
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\plurality_checkable_iterator.py", line 65, in _PopulateHead
    e = self.base_iterator.next()
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\wildcard_iterator.py", line 476, in IterAll
    expand_top_level_buckets=expand_top_level_buckets):
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\wildcard_iterator.py", line 177, in __iter__
    fields=get_fields)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\cloud_api_delegator.py", line 253, in GetObjectMetadata
    bucket_name, object_name, generation=generation, fields=fields)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\gcs_json_api.py", line 783, in GetObjectMetadata
    global_params=global_params)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\gslib\third_party\storage_apitools\storage_v1_client.py", line 1086, in Get
    download=download)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\third_party\apitools\apitools\base\py\base_api.py", line 720, in _RunMethod
    http, http_request, **opts)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 341, in MakeRequest
    check_response_func=check_response_func)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 391, in _MakeRequestNoRetry
    redirections=redirections, connection_type=connection_type)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\third_party\httplib2\python2\httplib2\__init__.py", line 1659, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\third_party\httplib2\python2\httplib2\__init__.py", line 1399, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\third_party\httplib2\python2\httplib2\__init__.py", line 1319, in _conn_request
    conn.connect()
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\third_party\httplib2\python2\httplib2\__init__.py", line 1069, in connect
    self.ssl_version, self.host)
  File "E:\ungoogled-chromium-windows\build\src\third_party\depot_tools\external_bin\gsutil\gsutil_4.28\gsutil\third_party\httplib2\python2\httplib2\__init__.py", line 97, in _ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=hostname)
  File "C:\Users\someuser\AppData\Local\Programs\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python\bin\Lib\ssl.py", line 369, in wrap_socket
    _context=self)
  File "C:\Users\someuser\AppData\Local\Programs\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python\bin\Lib\ssl.py", line 599, in __init__
    self.do_handshake()
  File "C:\Users\someuser\AppData\Local\Programs\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python\bin\Lib\ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:727)
Traceback (most recent call last):
  File "build/src/tools/update_pgo_profiles.py", line 154, in <module>
    sys.exit(main())
  File "build/src/tools/update_pgo_profiles.py", line 150, in main
    return args.func(args)
  File "build/src/tools/update_pgo_profiles.py", line 90, in _update
    raise RuntimeError('gsutil failed to download "%s"' % gs_path)
RuntimeError: gsutil failed to download "gs://chromium-optimization-profiles/pgo_profiles/chrome-win64-4606-1632147900-c5fefe97ce543e9ae30eae162df995bba6bc91d1.profdata"
```

**Comment by Nifury** [comment]
It probably has something to do with GFW. Maybe try a VPN out?

**Comment by Nifury** [comment]
Unlike VPNs, a program will not use http proxy unless it explicitly supports it. 
You might need to configure depot_tools to use http proxy. 

http://looooj.github.io/blog/depot_tools/2016/11/27/depot_tools.html
https://gist.github.com/nickdiego/2b2faa35f5ab48e7438ee434d2756765

**Comment by playgithub** [comment]
path\to\depot_tools\depot_tools.gitconfig
```cfg
[http]
proxy = http://127.0.0.1:8889
[https]
proxy = http://127.0.0.1:8889
```

path\to\depot_tools\g.bat
```cmd
set HTTP_PROXY=http://127.0.0.1:8889
set HTTPS_PROXY=http://127.0.0.1:8889
set PATH=path\to\depot_tools;%PATH%
gclient.bat
```

```cmd
g.bat
(no error)
```

%USERPROFILE%\.boto
```cfg
[Boto]
proxy = 127.0.0.1
proxy_port = 8889
proxy_type = http
```
```cmd
set PATH=path\to\depot_tools;%PATH%
set NO_AUTH_BOTO_CONFIG=%USERPROFILE%\.boto
py build/src/tools/update_pgo_profiles.py --target=win64 update --gs-url-base=chromium-optimization-profiles/pgo_profiles
INFO 1010 16:38:15.220000 util.py] Retrying request, attempt #3...                                                                                                                                                                           INFO 1010 16:38:26.637000 util.py] Retrying request, attempt #4...                                                                                                                                                                           INFO 1010 16:38:42.219000 util.py] Retrying request, attempt #5...                                                                                                                                                                           INFO 1010 16:39:16.939000 util.py] Retrying request, attempt #6... 
...
```

**Comment by Nifury** [comment]
No idea, but it seems that depot_tools doesn't use the proxy to download the pgo profile. 
You can disable GPO and ThinLTO if VPN is not an option.
